Mobile App for Lottery Addiction

Many people start playing the lottery for fun, but for some this activity turns into a habit which eventually escalates into addiction. Like other compulsive gamblers, lottery addicts soon begin spending from their savings and loans, they start to accumulate debts, and eventually engage in desperate behaviors like theft.

A medical institute that aims to prevent and treat gambling addictions wants to build a dedicated mobile app to help lottery addicts better estimate their chances of winning. The institute has a team of engineers that will build the app, but they need us to create the logical core of the app and calculate probabilities.

For the first version of the app, they want us to focus on the 6/49 lottery and build functions that enable users to answer questions like:

What is the probability of winning the big prize with a single ticket?

What is the probability of winning the big prize if we play 40 different tickets (or any other number)?

What is the probability of having at least five (or four, or three, or two) winning numbers on a single ticket?

The institute also wants us to consider historical data coming from the national 6/49 lottery game in Canada. The data set has data for 3,665 drawings, dating from 1982 to 2018 (we'll come back to this).

GOAL OF THE PROJECT

our goal is to write code that can enable users to answer probability questions about playing the lottery

1. Core Functions

we'll start by writing two functions that we'll use often:

a. A function that calculates factorials; and
b. A function that calculates combinations.

In the 6/49 lottery, six numbers are drawn from a set of 49 numbers that range from 1 to 49. The drawing is done without replacement, which means once a number is drawn, it's not put back in the set

In [19]:
def factorial(n):
    final_product = 1
    for i in range(n, 0, -1):
        final_product *= i
    return final_product

def combinations(n, k):
    numerator = factorial(n)
    denominator = factorial(k) * factorial(n-k)
    return numerator/denominator
    
    

2. One-ticket Probability

A player wins the big prize if the six numbers on their tickets match all the six numbers drawn

If a player has a ticket with the numbers {13, 22, 24, 27, 42, 44}, he only wins the big prize if the numbers drawn are {13, 22, 24, 27, 42, 44}. If only one number differs, he doesn't win.

For the first version of the app, we want players to be able to calculate the probability of winning the big prize with the various numbers they play on a single ticket (for each ticket a player chooses six numbers out of 49). So, we'll start by building a function that calculates the probability of winning the big prize for any given ticket.

We discussed with the engineering team of the medical institute, and they told us we need to be aware of the following details when we write the function:

Inside the app, the user inputs six different numbers from 1 to 49.
Under the hood, the six numbers will come as a Python list, which will serve as the single input to our function.
The engineering team wants the function to print the probability value in a friendly way — in a way that people without any probability training are able to understand.

In [20]:
def one_ticket_probability(unique_numbers):
    total_poss_outcomes = combinations(49,6)
    succ_outcomes = 1/total_poss_outcomes
    probability_perc = succ_outcomes * 100
    
    print('''Your chances to win the big prize with the numbers {} are {:.7f}%.
In other words, you have a 1 in {:,} chances to win.'''.format(unique_numbers,
                    probability_perc, int(total_poss_outcomes)))

In [21]:
#Lets test our function above
test_input = [3,4,8,7,2,3]
one_ticket_probability(test_input)

Your chances to win the big prize with the numbers [3, 4, 8, 7, 2, 3] are 0.0000072%.
In other words, you have a 1 in 13,983,816 chances to win.


In [22]:
test_input2 = [33,48,12,32,4,13]
one_ticket_probability(test_input2)

Your chances to win the big prize with the numbers [33, 48, 12, 32, 4, 13] are 0.0000072%.
In other words, you have a 1 in 13,983,816 chances to win.


In [23]:
test_input3= [4,7,6,5,4,3]
one_ticket_probability(test_input3)

Your chances to win the big prize with the numbers [4, 7, 6, 5, 4, 3] are 0.0000072%.
In other words, you have a 1 in 13,983,816 chances to win.


3. Historical Data Check for Canada Lottery

users should also be able to compare their ticket against the historical lottery data in Canada and determine whether they would have ever won by now.

we'll focus on exploring the historical data coming from the Canada 6/49 lottery

The data set contains historical data for 3,665 drawings (each row shows data for a single drawing), dating from 1982 to 2018. For each drawing, we can find the six numbers drawn in the following six columns:

NUMBER DRAWN 1
NUMBER DRAWN 2
NUMBER DRAWN 3
NUMBER DRAWN 4
NUMBER DRAWN 5
NUMBER DRAWN 6

In [24]:
#lets open the Canada Lottery file
import pandas as pd
canada_lottery = pd.read_csv('649.csv')

In [25]:
#explore the rows and columns
canada_lottery.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3665 entries, 0 to 3664
Data columns (total 11 columns):
PRODUCT            3665 non-null int64
DRAW NUMBER        3665 non-null int64
SEQUENCE NUMBER    3665 non-null int64
DRAW DATE          3665 non-null object
NUMBER DRAWN 1     3665 non-null int64
NUMBER DRAWN 2     3665 non-null int64
NUMBER DRAWN 3     3665 non-null int64
NUMBER DRAWN 4     3665 non-null int64
NUMBER DRAWN 5     3665 non-null int64
NUMBER DRAWN 6     3665 non-null int64
BONUS NUMBER       3665 non-null int64
dtypes: int64(10), object(1)
memory usage: 315.0+ KB


The file has 11 columns and 3665 entries

In [26]:
#Lets print the first and last 3 rows of the file to get familiar with the dataset
canada_lottery.head(3)


PRODUCT  DRAW NUMBER  SEQUENCE NUMBER  DRAW DATE  NUMBER DRAWN 1  \
0      649            1                0  6/12/1982               3   
1      649            2                0  6/19/1982               8   
2      649            3                0  6/26/1982               1   

   NUMBER DRAWN 2  NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  \
0              11              12              14              41   
1              33              36              37              39   
2               6              23              24              27   

   NUMBER DRAWN 6  BONUS NUMBER  
0              43            13  
1              41             9  
2              39            34

In [27]:
canada_lottery.tail(3)

PRODUCT  DRAW NUMBER  SEQUENCE NUMBER  DRAW DATE  NUMBER DRAWN 1  \
3662      649         3589                0  6/13/2018               6   
3663      649         3590                0  6/16/2018               2   
3664      649         3591                0  6/20/2018              14   

      NUMBER DRAWN 2  NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  \
3662              22              24              31              32   
3663              15              21              31              38   
3664              24              31              35              37   

      NUMBER DRAWN 6  BONUS NUMBER  
3662              34            16  
3663              49             8  
3664              48            17

4. Function for Historical Data Check

In [28]:
# We will extract all the winning six numbers from the historical dataset as python set
def extract_numbers(row):
    row = row[4:10]
    row = set(row.values)
    return row

winning_numbers = canada_lottery.apply(extract_numbers, axis=1)
winning_numbers.head()

0    {3, 41, 11, 12, 43, 14}
1    {33, 36, 37, 39, 8, 41}
2     {1, 6, 39, 23, 24, 27}
3     {3, 9, 10, 43, 13, 20}
4    {34, 5, 14, 47, 21, 31}
dtype: object

In [29]:
def check_historical_occurence(unique_numbers, historical_numbers):
    '''
    user_numbers: a Python list
    historical numbers: a pandas Series
    '''
    
    user_numbers_set = set(unique_numbers)
    check_occurrence = historical_numbers == user_numbers_set
    n_occurrences = check_occurrence.sum()
    
    if n_occurrences == 0:
        print('''The combination {} has never occured.
This doesn't mean it's more likely to occur now. Your chances to win the big prize in the next drawing using the combination {} are 0.0000072%.
In other words, you have a 1 in 13,983,816 chances to win.'''.format(unique_numbers, unique_numbers))
        
    else:
        print('''The number of times combination {} has occured in the past is {}.
Your chances to win the big prize in the next drawing using the combination {} are 0.0000072%.
In other words, you have a 1 in 13,983,816 chances to win.'''.format(unique_numbers, n_occurrences,
                                                                            unique_numbers))
    

In [30]:
#lets test our function above
input_test4 = [21,5,6,1,37]
check_historical_occurence(input_test4, winning_numbers)

The combination [21, 5, 6, 1, 37] has never occured.
This doesn't mean it's more likely to occur now. Your chances to win the big prize in the next drawing using the combination [21, 5, 6, 1, 37] are 0.0000072%.
In other words, you have a 1 in 13,983,816 chances to win.


In [31]:
input_test5 = [17,45,36,11,47]
check_historical_occurence(input_test5, winning_numbers)

The combination [17, 45, 36, 11, 47] has never occured.
This doesn't mean it's more likely to occur now. Your chances to win the big prize in the next drawing using the combination [17, 45, 36, 11, 47] are 0.0000072%.
In other words, you have a 1 in 13,983,816 chances to win.


5. Multi-ticket Probability

Lottery addicts usually play more than one ticket on a single drawing, thinking that this might increase their chances of winning significantly.

Our purpose is to help them better estimate their chances of winning we're going to write a function that will allow the users to calculate the chances of winning for any number of different tickets.

We've talked with the engineering team and they gave us the following information:

The user will input the number of different tickets they want to play (without inputting the specific combinations they intend to play).
Our function will see an integer between 1 and 13,983,816 (the maximum number of different tickets).
The function should print information about the probability of winning the big prize depending on the number of different tickets played

In [32]:
def multi_ticket_probability(number_of_tickets):
    total_poss_outcomes = combinations(49,6)
    succ_outcomes = number_of_tickets/total_poss_outcomes
    percentage_form = succ_outcomes * 100
    
    if number_of_tickets == 1:
        print('''Your chances to win the big prize with one ticket are {:.6f}%.
In other words, you have a 1 in {:,} chances to win.'''.format(percentage_form, int(succ_outcomes)))
    
    else:
        combinations_simplified = round(succ_outcomes / number_of_tickets)   
        print('''Your chances to win the big prize with {:,} different tickets are {:.6f}%.
In other words, you have a 1 in {:,} chances to win.'''.format(number_of_tickets, percentage_form,
                                                               combinations_simplified))
    

In [35]:
#Let test our function above
test_input6 = [1, 10, 100, 10000, 1000000, 6991908, 13983816]

for test_input in test_input6:
    multi_ticket_probability(test_input)
    print('------------------------') # output delimiter

Your chances to win the big prize with one ticket are 0.000007%.
In other words, you have a 1 in 0 chances to win.
------------------------
Your chances to win the big prize with 10 different tickets are 0.000072%.
In other words, you have a 1 in 0 chances to win.
------------------------
Your chances to win the big prize with 100 different tickets are 0.000715%.
In other words, you have a 1 in 0 chances to win.
------------------------
Your chances to win the big prize with 10,000 different tickets are 0.071511%.
In other words, you have a 1 in 0 chances to win.
------------------------
Your chances to win the big prize with 1,000,000 different tickets are 7.151124%.
In other words, you have a 1 in 0 chances to win.
------------------------
Your chances to win the big prize with 6,991,908 different tickets are 50.000000%.
In other words, you have a 1 in 0 chances to win.
------------------------
Your chances to win the big prize with 13,983,816 different tickets are 100.000000%.
In ot

6· Less Winning Numbers — Function

So far, we wrote three main functions:

one_ticket_probability() — calculates the probability of winning the big prize with a single ticket

check_historical_occurrence() — checks whether a certain combination has occurred in the Canada lottery data set

multi_ticket_probability() — calculates the probability for any number of tickets between 1 and 13,983,816

On this screen, we're going to write one more function to allow the users to calculate probabilities for two, three, four, or five winning numbers.

For extra context, in most 6/49 lotteries there are smaller prizes if a player's ticket match two, three, four, or five of the six numbers drawn. As a consequence, the users might be interested in knowing the probability of having two, three, four, or five winning numbers.

In [41]:
#Lets write the function 
def probability_less_6(n_winning_numbers):
    n_combinations_used = combinations(6,n_winning_numbers)
    n_combinations_rem = combinations(43, 6 - n_winning_numbers)
    probability = n_winning_numbers/n_combinations_rem
    successful_outcomes = n_combinations_used * n_combinations_rem
    
    n_combinations_total = combinations(49, 6)    
    probability = successful_outcomes / n_combinations_total
    
    probability_percentage = probability * 100    
    combinations_simplified = round(n_combinations_total/successful_outcomes)    
    print('''Your chances of having {} winning numbers with this ticket are {:.6f}%.
In other words, you have a 1 in {:,} chances to win.'''.format(n_winning_numbers, probability_percentage,
                                                               int(combinations_simplified)))

In [42]:
#lets test the input
for test_input in [2, 3, 4, 5]:
    probability_less_6(test_input)
    print('--------------------------') # output delimiter

Your chances of having 2 winning numbers with this ticket are 13.237803%.
In other words, you have a 1 in 8 chances to win.
--------------------------
Your chances of having 3 winning numbers with this ticket are 1.765040%.
In other words, you have a 1 in 57 chances to win.
--------------------------
Your chances of having 4 winning numbers with this ticket are 0.096862%.
In other words, you have a 1 in 1,032 chances to win.
--------------------------
Your chances of having 5 winning numbers with this ticket are 0.001845%.
In other words, you have a 1 in 54,201 chances to win.
--------------------------


Next steps
For the first version of the app, we coded four main functions:

one_ticket_probability() — calculates the probability of winning the big prize with a single ticket
check_historical_occurrence() — checks whether a certain combination has occurred in the Canada lottery data set
multi_ticket_probability() — calculates the probability for any number of of tickets between 1 and 13,983,816
probability_less_6() — calculates the probability of having two, three, four or five winning numbers exactly
Possible features for a second version of the app include:

Making the outputs even easier to understand by adding fun analogies (for example, we can find probabilities for strange events and compare with the chances of winning in lottery; for instance, we can output something along the lines "You are 100 times more likely to be the victim of a shark attack than winning the lottery")
Combining the one_ticket_probability() and check_historical_occurrence() to output information on probability and historical occurrence at the same time
Create a function similar to probability_less_6() which calculates the probability of having at least two, three, four or five winning numbers. Hint: the number of successful outcomes for having at least four winning numbers is the sum of these three numbers:
The number of successful outcomes for having four winning numbers exactly
The number of successful outcomes for having five winning numbers exactly
The number of successful outcomes for having six winning numbers exactly